trigger: none
resources:
  - repo: self
variables: 
  - group: variable-${{parameters.Environment}}

parameters:
- name: Environment
  displayName: Environment
  type: string
  default: ""
  values:
    - dev
    - test
    - prod

- name: doThing
  default: true
  type: boolean

stages:
- stage: Deployment${{parameters.Environment}}
  displayName: ${{parameters.Environment}}
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Bash@3
      displayName: Terraform Initialization
      inputs:
        targetType: inline
        workingDirectory: $(Build.SourcesDirectory)/terraform
        script: terraform init -backend-config=../${{parameters.Environment}}/backend.tf

    - task: Bash@3
      displayName: terraform validate
      inputs:
        targetType: inline
        script: echo $(ARM_CLIENT_ID)
        workingDirectory: $(Build.SourcesDirectory)/terraform

    - task: Bash@3
      displayName: terraform planning State
      inputs:
        targetType: inline
        script: terraform plan -var="environment=${{parameters.Environment}}"
        workingDirectory: $(Build.SourcesDirectory)/terraform

    - task: Bash@3
      displayName: terraform planning State
      inputs:
        targetType: inline
        script: terraform apply -auto-approve -var="environment=${{parameters.Environment}}"
        workingDirectory: $(Build.SourcesDirectory)/terraform

    # - task: Bash@3
    #   displayName: terraform plan
    #   inputs:
    #     targetType: 'inline'
    #     script: terraform plan
    #     workingDirectory: $(Build.SourcesDirectory)/terraform

    # - task: Bash@3
    #   displayName: Resource Create
    #   inputs:
    #     targetType: 'inline'
    #     script: terraform apply -auto-approve -var="environment=${{parameters.Environment}}"
    #     workingDirectory: $(Build.SourcesDirectory)/terraform